name: WinForms CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: 'RazorPay.sln'
      Configuration: 'Release'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet packages
      run: msbuild ${{ env.Solution_Name }} /t:Restore /p:Configuration=${{ env.Configuration }}

    - name: Build solution
      run: msbuild ${{ env.Solution_Name }} /p:Configuration=${{ env.Configuration }}

    - name: Run tests
      run: msbuild ${{ env.Solution_Name }} /p:Configuration=${{ env.Configuration }} /t:Test

    - name: Publish application
      run: msbuild ${{ env.Solution_Name }} /p:Configuration=${{ env.Configuration }} /t:Publish
